TYPE_COMPLETE = 1
TYPE_REWRITE = 2


class Format:
    # end = '\033[0m'
    # underline = '\033[3m'
    end = '"'
    underline = '"'


exercises = [
    {
        "type": TYPE_COMPLETE,
        "tip": "Complete with to be or articles or opposites.",
        "questions": [
            ["What's ___ name?", ["your", "her", "his"]],
            ["My name ___ Tom.", ["is"]],
            ["I ___ Tom.", ["am", "'m"]],
            ["You ___ a doctor.", ["are", "'re"]],
            ["He ___ a dentist.", ["is", "'s"]],
            ["John and I ___ English students.", ["are"]],
            ["You ___ a doctor.", ["are"]],
            ["Jim ___ a college student.", ["is", "'s"]],
            ["Ruth and I ___ secretaries.", ["are"]],
            ["Mary ___ a secretary, too.", ["is", "'s"]],
            ["It ___ a book.", ["is", "'s"]],
            ["Robert ___ an executive.", ["is", "'s"]],
            ["You ___ nurses.", ["are", "'re"]],
            ["We ___ nurses, too.", ["are", "'re"]],
            ["I'm ___ student.", ["a"]],
            ["I'm ___ English student.", ["an"]],
            ["You're ___ actor.", ["an"]],
            ["he's ___ economist.", ["an"]],
            ["Mary's ___ secretary.", ["a"]],
            ["John's ___ executive.", ["an"]],
            ["It's ___ book.", ["a"]],
            ["Susan's ___ housewife.", ["a"]],
            ["Joe's ___ economist", ["an"]],
            ["He's ___ executive.", ["an"]],
            ["Mary's ___ politician.", ["a"]],
            ["It's ___ door.", ["a"]],
            ["Jane's ___ actress.", ["an"]],
            ["Robert is ___ executive.", ["an"]],
            ["Tom and Frank are ___ policemen.", [""]],
            ["Helen is ___ important woman.", ["an"]],
            ["Ruth and Richards are ___ engineers", [""]],
            ["Harry and Henry are ___ Americans.", [""]],
            ["John is ___ athlete.", ["an"]],
            ["Jonh is ___ college student.", ["a"]],
            ["Mary and Jane are ___ architects.", [""]],
            ["Harry is ___ English banker.", ["an"]],
            ["They are ___ dentists.", [""]],
            ["She's ___ doctor.", ["a"]],
            ["Jim's ___ executive.", ["an"]],
            ["Frank and Mary are ___ psychologists.", [""]],
            ["Are you a bad lawyer? No, I'm a ___ lawyer.", ["good"]],
            ["Is the secretary tall? No, She's ___.", ["short"]],
            ["Are the computers old? No, They're ___.", ["new"]],
            ["Are the office boys old? No, They're ___.", ["young"]],
            ["Is the dialog difficult? No, It's ___.", ["easy"]],
            ["Are the exercises hard? No, They're ___ ", ["easy"]],
            ["Is the bus slow? No, It's ___.", ["fast"]],
            ["Are the boys dumb? No, They're ___ ", ["smart", ["intelligent"]]],
            ["___ is the first month.", ["January"]],
            ["January is ___ month.", ["the fist"]],
            ["___ is the second month.", ["February"]],
            ["February is ___ month.", ["the second"]],
            ["___ is the third month.", ["March"]],
            ["___ is the fourth month.", ["April"]],
            ["May is ___ month.", ["the fifth"]],
            ["___ is the sixth month.", ["June"]],
            ["August is ___ month.", ["the eighth"]],
            ["September is ___ month.", ["the ninth"]],
            ["October is ___ month.", ["the tenth"]],
            ["___ is the tenth month.", ["October"]],
            ["November is ___ month.", ["the eleventh"]],
            ["___ is the eleventh month.", ["November"]],
            ["December is ___ month.", ["the twelfth"]],
            ["___ is the twelfth month.", ["December"]],
            ["What time is dinner? Dinner is ___ 7 p.m.", ["at"]],
            ["What time is dinner? Dinner is at 7 ___.", ["p.m"]],
            ["What time is the movie? The movie is ___ 8 p.m.", ["at"]],
            ["What time is the movie? The movie is at 8 ___.", ["p.m"]],
            ["What time is breakfast? Breakfast is ___ 7 a.m.", ["at"]],
            ["What time is breakfast? Breakfast is at 7 ___.", ["a.m"]],
            ["What time is the lunch? The Lunch is ___ noon.", ["at"]],
            ["The students are ___ class.", ["in"]],
            ["The surgeon is ___ the hospital.", ["at"]],
            ["The posters are ___ the wall.", ["on"]],
            ["The bike is ___ the garage.", ["in"]],
            ["The bank is ___ the city.", ["in"]],
            ["We're apartement is ___ 3654 Valentine Street.", ["at"]],
            ["Our is ___ Oak Avenue.", ["on"]],
            ["New York is ___ the United States.", ["in"]],
            ["The dentists are ___ work.", ["at"]],
            ["The expression is ___ the blackboard.", ["on"]],
            ["The lights are ___ the celling.", ["on"]],

            ["Is the police officer in ___ car?", ["his","her"]],
            ["Mary is at work. ___ office is in Leblon.", ["her"]],
            ["We're at ___ school.", ["our"]],
            ["Where is your professor? ___ professor is at the university.", ["My"]],
            ["Mary and Paul ___ party is on Sunday.", ["their"]],
            ["(Ruth and I) ___ birthday is on the 10th of May.", ["Our"]],
            ["Dick and I are in ___ work office.", ["our"]],
            ["(John and you) ___ pictures are very good.", ["Your"]],
            # [" ___ ", [""]],
            # [" ___ ", [""]],
            # [" ___ ", [""]],
            # [" ___ ", [""]],
            # [" ___ ", [""]],
        ]
    },
    {
        "type": TYPE_REWRITE,
        "tip": "Contractions",
        "questions": [
            ["You are a man.", "You're a man."],
            ["He is a pilot.", "He's a pilot."],
            ["She is a woman.", "She's a woman."],
            ["Jane is a housewife.", "Jane's a housewife."],
            # ["", ""],
        ]
    },
    {
        "type": TYPE_REWRITE,
        "tip": "Singular or plural",
        "questions": [
            ["He's an engineer.", "They're engineers."],
            ["I'm a pilot.", "We're pilots."],
            ["It's a book.", "They're books."],
            ["He's a doctor", "They're doctors."],
            ["He isn't an I.T professional.", "They aren't I.T professionals."],
            ["She isn't a nurse.", "They aren't nurses."],
            ["I'm not an economist.", "We aren't economists."],
            ["He isn't an English student.", "They aren't English students."],
            ["The book isn't here.", "The books aren't here."],
            ["Those are computers.", "That's a computer."],
            ["This is a lipstick.", "These are lipsticks."],
            ["That's a housewife.", "Those are housewives."],
            ["Those are erasers.", "That's an eraser."],
            ["This is a cigarette.", "These are cigarettes."],
            ["These are magazines.", "This is a magazine"],
            ["That's a subway station.", "Those are subway stations."],
            # ["", ""],
        ]
    },
    {
        "type": TYPE_REWRITE,
        "tip": "Negative",
        "questions": [
            ["The economist is here.", "The economist isn't here."],
            ["The architect is here.", "The architect isn't here."],
            ["The dentist is here.", "The dentist isn't here."],
            ["The college student is here.", "The college student isn't here."],
            # ["", ""],
        ]
    },
    {
        "type": TYPE_REWRITE,
        "tip": "Short answers:",
        "questions": [
            ["Is the lesson difficult?", ["No, It isn't.", "Yes, It is."]],
            ["Is your pen Japanese?", ["Yes, It is.", "No, It isn't"]],
            ["Is your car near the hospital?", ["Yes, It is.", "No, It isn't."]],
            ["Is the housewife pregnant?", ["No, She isn't.", "Yes, She is."]],
            ["Is the receptionist dumb?", ["No, She isn't.", "Yes, She is."]],
            # ["", ""],
        ]
    },
    {
        "type": TYPE_REWRITE,
        "tip": "Answer the questions.\nE.g.: No, these aren't my keys. Those are my keys.",
        "questions": [
            ["Is that your English book?", "No, that isn't my English book. This is my English book."],
            ["Are these your CDs?", "No, these aren't my CDs. Those are my CDs."],
            ["Is that your friend?", "No, that isn't my friend. This is my friend."],
        ]
    },
    {
        "type": TYPE_REWRITE,
        "tip": "Opposites. Use personal pronouns.",
        "questions": [
            ["The secretary isn't dumb, ", ["She's intelligent.", "She's smart."]],
            ["The taxi driver isn't fat, ", "He's thin."],
            ["The I.T professional isn't poor, ", "He's rich."],
            ["The pilot isn't old, ", "He's young."],
            ["His wife isn't well, ", "She's sick."],
            # ["", ""],
            # ["", ""],
        ]
    },
    {
        "type": TYPE_REWRITE,
        "tip": "Times. Don't worry about p.m or a.m.",
        "questions": [
            ["1:10", ["one and ten", "ten paste one"]],
            ["5:15", ["five and fifth", "a quarter paste five"]],
            ["3:50", ["three and fifty", "ten to four"]],
            ["6:00", ["six o'clock"]],
            ["11:45:", ["a quarter to noun", "a quarter to midday", "a quarter to launch", "a quarter to twelve", "eleven and forty five"]],
            ["10:40", ["twenty to eleven", "ten and forty"]],
            ["4:30", ["half paste four", "four and thirty"]],
            ["7:20", ["twenty paste seven", "seven and twenty"]],
            ["4:50", ["ten to five", "four and fifty"]],
            ["11:30", ["elevent and thirty", "half paste eleven"]],
            ["5:05", ["five paste five", "five and five"]],
            ["12:00", ["noun", "launch", "midday", "twelve o'clock"]],
            # ["", ""],d 
            # ["", ""],
        ]
    },
    {
        "type": TYPE_REWRITE,
        "tip": "Change the showed sentence to NEGATIVE or NEGATIVE INTERROGATIVE.",
        "questions": [
            ["Jane's in the hospital.", ["Jane isn't in the hospital.", "Isn't Jane in the hospital?"]],
            ["She's a teacher at Brasas.", ["She isn't a teacher at Brasas.", "Isn't She a teacher at Brasas?"]],
            ["The housewife is in the car.", ["The housewife isn't in the car.", "Isn't the housewife in the car?"]],
            ["The eraser is on the desk.", ["The eraser isn't on the desk.", "Isn't the eraser on the desk?"]],
            ["The light switch is on the wall.", [
                "The light switch isn't on the wall.",
                "Isn't the light switch on the wall?"
            ]],
            # ["", ["", ""]],
            # ["", ""],
        ]
    },
    {
        "type": TYPE_REWRITE,
        "tip": "Substitute the quotes words for personal pronouns.",
        "questions": [
            [Format.underline + "Richard and I" + Format.end + " are English students.", "We're English students."],
            [Format.underline + "Richard and Tom" + Format.end + " are pilots.", "They're pilots."],
            [Format.underline + "You and I" + Format.end + " are secretaries.", "We're secretaries"],
            [Format.underline + "Jim and I" + Format.end + " are economists.", "We're economists."],
            [Format.underline + "Mary" + Format.end + " is an engineer.", "She's an engineer."],
            [Format.underline + "Joe" + Format.end + " is an actor", "He's an actor."],
            [Format.underline + "My classroom" + Format.end + " is Room 1.", "It's Room 1."],
            [Format.underline + "The housewife" + Format.end + " is an english student, too.",
             "She's an English student, too."],
            [Format.underline + "Bill and you" + Format.end + " are doctors.", "You're doctors."],
            [Format.underline + "John and Mary" + Format.end + " are English teachers.", "They're english teachers."],
            # [Format.underline + "" + Format.end + "", ""],
            # [Format.underline + "" + Format.end + "", ""],
            # [Format.underline + "" + Format.end + "", ""],
        ]
    },
]